name: Deploy

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release'
        required: False
        default: '1.0'
  push:
    branches:
      - main

jobs:
  create-env:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env.prod file
        run: |
          touch .env.prod
          echo DATABASE_URL=${{secrets.DATABASE_URL}} >> .env.prod
          cat .env.prod
      - name: Upload .env.prod
        uses: actions/upload-artifact@v2
        with:
          name: .env.prod
          path: .env.prod
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs: create-env
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve .env.prod
        uses: actions/download-artifact@v2
        with:
          name: .env.prod
          path: .env.prod
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'unity-checkers'
          heroku_email: 'aferron@uoguelph.ca'
          usedocker: true
